# Generated by Django 6.0.4 on 2026-05-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок поста')),
                ('text', models.TextField(verbose_name='Текст поста')),
                ('media', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Медиа-файлы поста')),
            ],
        ),
    ]
