# Generated by Django 6.0.4 on 2026-05-06 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='dislike_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Кол-во дизлайков под постом'),
        ),
        migrations.AddField(
            model_name='posts',
            name='like_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Кол-во лайков под постом'),
        ),
        migrations.CreateModel(
            name='PostsAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('none', 'None')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]
