# Generated by Django 6.0 on 2026-06-01 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_dislike_count_posts_like_count_postsaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('like_count', models.IntegerField(blank=True, default=0, verbose_name='Кол-во лайков под постом')),
                ('dislike_count', models.IntegerField(blank=True, default=0, verbose_name='Кол-во дизлайков под постом')),
                ('state', models.BooleanField(null=True, verbose_name='True - like, False - dislike, None - not yet')),
                ('parentId', models.IntegerField(null=True, verbose_name='ID родительского коммента (если нет - null/none)')),
                ('locateZ', models.IntegerField(null=True, verbose_name='Z-index комментария относительно тайтла (0 уровень)')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
