# Generated by Django 6.0 on 2026-06-13 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postcommentaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Имя тайтла')),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image:')),
                ('user_name', models.TextField(verbose_name='Логин пользователя:')),
                ('user_rating', models.IntegerField(blank=True, null=True, verbose_name='Оценка пользователя:')),
                ('user_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий пользователя:')),
                ('like_count', models.IntegerField(verbose_name='Кол-во лайков под постом')),
                ('dislike_count', models.IntegerField(verbose_name='Кол-во дизлайков под постом')),
                ('state', models.BooleanField(blank=True, null=True, verbose_name='True - like, False - dislike, None - not yet')),
                ('parentId', models.IntegerField(blank=True, null=True, verbose_name='ID родительского коммента (если нет - null/none)')),
                ('locateZ', models.IntegerField(blank=True, null=True, verbose_name='Z-index комментария относительно тайтла (0 уровень)')),
            ],
        ),
        migrations.RenameModel(
            old_name='PostCommentAction',
            new_name='PostCommentsAction',
        ),
        migrations.AlterField(
            model_name='postcommentsaction',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.postcomments'),
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
