# Generated by Django 6.0 on 2026-06-13 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_postcomments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomments',
            name='name',
        ),
        migrations.RemoveField(
            model_name='postcomments',
            name='user_image',
        ),
        migrations.RemoveField(
            model_name='postcomments',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='postcomments',
            name='user_rating',
        ),
        migrations.AddField(
            model_name='postcomments',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.posts'),
        ),
        migrations.AddField(
            model_name='postcomments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
