# Generated by Django 6.0 on 2026-06-13 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_postcomments_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomments',
            name='parentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.postcomments'),
        ),
    ]
