# Generated by Django 6.0 on 2026-06-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_postcomments_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomments',
            name='parentId',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID родительского коммента (если нет - null/none)'),
        ),
    ]
