# Generated by Django 5.1.4 on 2025-09-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tags_alter_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tag',
            new_name='name',
        ),
    ]
