# Generated by Django 5.1.4 on 2025-09-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.DateField(verbose_name='Когда вышел (сезон)'),
        ),
    ]
