# Generated by Django 5.1.4 on 2025-09-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.TextField(max_length=3, verbose_name='Рейтинг'),
        ),
    ]
