# Generated by Django 5.1.4 on 2025-09-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age_rating',
            field=models.IntegerField(default=13, max_length=2, verbose_name='Возрастной рейтинг'),
            preserve_default=False,
        ),
    ]
