# Generated by Django 5.1.4 on 2025-09-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_product_age_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age_rating',
            field=models.IntegerField(verbose_name='Возрастной рейтинг'),
        ),
    ]
