# Generated by Django 5.1.4 on 2025-09-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_product_age_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_manager',
            field=models.CharField(max_length=100, null=True, verbose_name='Студия выпуска'),
        ),
    ]
