# Generated by Django 5.1.4 on 2025-09-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_product_product_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='episods',
            field=models.TextField(null=True, verbose_name='Кол-во эпизодов'),
        ),
    ]
