# Generated by Django 5.1.4 on 2025-09-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_product_episods'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.TextField(null=True, verbose_name='Статус Тайтла (Вышел\\Онгоинг)'),
        ),
    ]
