# Generated by Django 5.1.4 on 2025-09-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Album_Pics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ManyToManyField(related_name='pics', to='main.pics')),
            ],
        ),
    ]
