# Generated by Django 5.1.4 on 2025-09-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_pics_album_pics'),
    ]

    operations = [
        migrations.AddField(
            model_name='album_pics',
            name='name',
            field=models.TextField(null=True, verbose_name='Название Альбома (для какого тайтла)'),
        ),
    ]
