# Generated by Django 5.1.4 on 2025-09-04 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weblinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True, verbose_name='Название сайта')),
                ('link', models.TextField(null=True, verbose_name='Ссылка на сайт:')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='eng_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Английское название'),
        ),
        migrations.AddField(
            model_name='product',
            name='trailer',
            field=models.URLField(blank=True, null=True, verbose_name='Трейлер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.status'),
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(verbose_name='Имя')),
                ('second_name', models.TextField(null=True, verbose_name='Фамилия')),
                ('age', models.IntegerField(null=True, verbose_name='Возраст')),
                ('description', models.TextField(verbose_name='Всё о герое, где появляется, что делал и т.д. и т.п.')),
                ('products', models.ManyToManyField(related_name='products_in', to='main.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='characters',
            field=models.ManyToManyField(related_name='other_characters', to='main.characters'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_characters',
            field=models.ManyToManyField(related_name='main_characters', to='main.characters'),
        ),
        migrations.CreateModel(
            name='Voice_maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(verbose_name='Имя')),
                ('second_name', models.TextField(null=True, verbose_name='Фамилия')),
                ('age', models.IntegerField(null=True, verbose_name='Возраст')),
                ('products_in', models.ManyToManyField(related_name='product_in', to='main.product')),
            ],
        ),
        migrations.AddField(
            model_name='characters',
            name='voice_makers',
            field=models.ManyToManyField(related_name='voices', to='main.voice_maker'),
        ),
        migrations.AddField(
            model_name='product',
            name='links',
            field=models.ManyToManyField(related_name='links', to='main.weblinks'),
        ),
    ]
