# Generated by Django 5.1.4 on 2025-09-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_weblinks_product_eng_name_product_trailer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Картинка'),
        ),
    ]
