# Generated by Django 5.1.4 on 2025-09-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_characters_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='link_to_wiki',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на вики'),
        ),
    ]
