# Generated by Django 5.1.4 on 2025-09-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_characters_link_to_wiki'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='season_info',
            field=models.TextField(null=True, verbose_name='Пересказ сезона:'),
        ),
    ]
