# Generated by Django 5.1.4 on 2025-09-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_product_season_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.TextField(null=True, verbose_name='Comments'),
        ),
    ]
