# Generated by Django 5.1.4 on 2025-09-11 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_product_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comments',
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(verbose_name='Логин пользователя:')),
                ('user_rating', models.IntegerField(verbose_name='Оценка пользователя:')),
                ('user_comment', models.TextField(null=True, verbose_name='Комментарий пользователя:')),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_name', to='main.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.ManyToManyField(related_name='comments', to='main.comments'),
        ),
    ]
