# Generated by Django 5.1.4 on 2025-09-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_product_comments_comments_product_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comments',
        ),
    ]
