# Generated by Django 5.1.4 on 2025-09-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_product_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='product_name',
            field=models.TextField(null=True, verbose_name='Имя тайтла'),
        ),
    ]
