# Generated by Django 5.1.4 on 2025-09-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_comments_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='product_name',
            new_name='name',
        ),
    ]
