# Generated by Django 5.1.4 on 2025-09-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_rename_product_name_comments_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='dislike_count',
            field=models.IntegerField(null=True, verbose_name='Кол-во дизлайков под постом'),
        ),
        migrations.AddField(
            model_name='comments',
            name='like_count',
            field=models.IntegerField(null=True, verbose_name='Кол-во лайков под постом'),
        ),
    ]
