# Generated by Django 5.1.4 on 2025-09-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_comments_dislike_count_comments_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='dislike_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во дизлайков под постом'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во лайков под постом'),
            preserve_default=False,
        ),
    ]
