# Generated by Django 5.1.4 on 2025-09-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_comments_dislike_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='state',
            field=models.BooleanField(null=True, verbose_name='True - like, False - dislike, None - not yet'),
        ),
    ]
