# Generated by Django 5.1.4 on 2025-09-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Image:'),
        ),
    ]
