# Generated by Django 5.1.4 on 2025-09-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatars/null_avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
