# Generated by Django 5.1.4 on 2025-09-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_commentaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaction',
            name='action_type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('none', 'None')], max_length=10),
        ),
    ]
