# Generated by Django 6.0 on 2025-12-05 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_useractivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
