# Generated by Django 6.0 on 2025-12-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_useractivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='voice_makers',
            field=models.ManyToManyField(null=True, related_name='voices', to='main.voice_maker'),
        ),
    ]
