# Generated by Django 6.0 on 2025-12-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_alter_characters_voice_makers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voice_maker',
            name='products_in',
        ),
    ]
