# Generated by Django 6.0 on 2025-12-15 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_remove_voice_maker_products_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characters',
            name='voice_makers',
        ),
    ]
