# Generated by Django 6.0 on 2026-01-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_profile_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pics',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
