# Generated by Django 6.0 on 2026-01-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_alter_pics_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pics',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
