# Generated by Django 6.0 on 2026-01-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pics',
            name='image',
            field=models.ImageField(null=True, upload_to='img/pics/', verbose_name='Изображение'),
        ),
    ]
