# Generated by Django 6.0 on 2026-01-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_aimessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessages',
            name='ai',
            field=models.TextField(null=True),
        ),
    ]
