# Generated by Django 6.0 on 2026-01-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_aimessages_ai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimessages',
            name='ai',
            field=models.TextField(),
        ),
    ]
