# Generated by Django 6.0 on 2026-01-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_alter_aimessages_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessages',
            name='role',
            field=models.TextField(default='user', null=True),
        ),
    ]
