# Generated by Django 6.0 on 2026-02-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_aimessages_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='alter_pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Альтернативный доступ к картинке (если ссылка отвалилась)'),
        ),
    ]
