# Generated by Django 6.0 on 2026-02-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_characters_alter_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characters',
            field=models.ManyToManyField(null=True, related_name='other_characters', to='main.characters'),
        ),
        migrations.AlterField(
            model_name='product',
            name='links',
            field=models.ManyToManyField(null=True, related_name='links', to='main.weblinks'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_characters',
            field=models.ManyToManyField(null=True, related_name='main_characters', to='main.characters'),
        ),
    ]
