# Generated by Django 6.0 on 2026-02-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_alter_product_characters_alter_product_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='locateZ',
            field=models.CharField(null=True, verbose_name='Z-index комментария относительно тайтла (0 уровень)'),
        ),
    ]
