# Generated by Django 6.0 on 2026-02-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_product_locatez'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='locateZ',
        ),
        migrations.AddField(
            model_name='comments',
            name='locateZ',
            field=models.CharField(null=True, verbose_name='Z-index комментария относительно тайтла (0 уровень)'),
        ),
    ]
