# Generated by Django 6.0 on 2026-02-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_remove_product_locatez_comments_locatez'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='parentId',
            field=models.CharField(null=True, verbose_name='ID родительского коммента (если нет - null)'),
        ),
    ]
