# Generated by Django 6.0 on 2026-02-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_comments_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='parentId',
            field=models.CharField(null=True, verbose_name='ID родительского коммента (если нет - null/none)'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_rating',
            field=models.IntegerField(null=True, verbose_name='Оценка пользователя:'),
        ),
    ]
