# Generated by Django 6.0 on 2026-02-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_alter_comments_parentid_alter_comments_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='locateZ',
            field=models.IntegerField(null=True, verbose_name='Z-index комментария относительно тайтла (0 уровень)'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='parentId',
            field=models.IntegerField(null=True, verbose_name='ID родительского коммента (если нет - null/none)'),
        ),
    ]
