# Generated by Django 6.0 on 2026-03-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_alter_comments_locatez_alter_comments_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='avatars/'),
        ),
    ]
