# Generated by Django 6.0 on 2026-03-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default="{% static '/img/null_avatar.png' %}", upload_to='avatars/'),
        ),
    ]
