# Generated by Django 6.0 on 2026-03-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characters',
            name='products',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='avatars/null_avatar.png', upload_to='avatars/'),
        ),
    ]
