# Generated by Django 6.0 on 2026-04-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(max_length=3, verbose_name='Рейтинг'),
        ),
    ]
