# Generated by Django 6.0 on 2026-04-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age_rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возрастной рейтинг'),
        ),
    ]
