# Generated by Django 6.0 on 2026-04-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_alter_product_age_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='eng_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Английское название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='episods',
            field=models.CharField(null=True, verbose_name='Кол-во эпизодов'),
        ),
        migrations.AlterField(
            model_name='product',
            name='links',
            field=models.ManyToManyField(blank=True, null=True, related_name='links', to='main.weblinks'),
        ),
        migrations.AlterField(
            model_name='product',
            name='season_info',
            field=models.TextField(blank=True, null=True, verbose_name='Пересказ сезона:'),
        ),
    ]
