# Generated by Django 6.0.4 on 2026-05-06 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_alter_product_eng_name_alter_product_episods_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characters',
            field=models.ManyToManyField(blank=True, null=True, related_name='other_characters', to='main.characters'),
        ),
        migrations.AlterField(
            model_name='product',
            name='episods',
            field=models.CharField(max_length=5, null=True, verbose_name='Кол-во эпизодов'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_characters',
            field=models.ManyToManyField(blank=True, null=True, related_name='main_characters', to='main.characters'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Студия выпуска'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='main.tags'),
        ),
        migrations.CreateModel(
            name='PublicPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True, verbose_name='Оглавление')),
                ('text', models.TextField(null=True, verbose_name='Текст')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
