# Generated by Django 6.0 on 2026-06-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_alter_product_characters_alter_product_episods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='Ранг пользователя'),
        ),
    ]
