# Generated by Django 6.0 on 2026-06-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_profile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='color',
            field=models.TextField(default='white', verbose_name='Цвет пользователя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, null=True, to='main.product'),
        ),
    ]
