# Generated by Django 6.0 on 2026-06-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_alter_profilestats_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='locateZ',
            field=models.IntegerField(blank=True, null=True, verbose_name='Z-index комментария относительно тайтла (0 уровень)'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Имя тайтла'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='parentId',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID родительского коммента (если нет - null/none)'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='state',
            field=models.BooleanField(blank=True, null=True, verbose_name='True - like, False - dislike, None - not yet'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий пользователя:'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image:'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка пользователя:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, to='main.product'),
        ),
    ]
