# Generated by Django 6.0 on 2026-08-05 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_alter_comments_user_alter_comments_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user_image',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user_name',
        ),
    ]
