# Generated by Django 6.0 on 2026-08-05 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_remove_comments_user_image_remove_comments_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='album_pics',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='main.product'),
        ),
    ]
