# Generated by Django 6.0 on 2026-08-19 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_album_pics_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_seconds',
            field=models.IntegerField(default=0, verbose_name='Время активности'),
        ),
        migrations.AlterField(
            model_name='album_pics',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product'),
        ),
    ]
